run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: false
    exclude-functions:
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Fprint
      - fmt.Scanln
      - (io.Closer).Close
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/remote/remote.go
      text: "InsecureIgnoreHostKey"
    - linters:
        - errcheck
      text: "Error return value of .*(Save|Set|Start|Write).*is not checked"
